### ISSUE TITLE
svg width, height auto 속성을 주면 브라우저 콘솔에서 에러

### ISSUE THREAD

**Issue by kimploo** [fe-codecrafters/baekseolgi#37]
동작은 얼추 잘 되는데 콘솔에서는 에러가 나는 모습

![Screenshot 2023-11-07 at 12 27 54 AM](https://github.com/fe-codecrafters/baekseolgi/assets/12145019/ccf9c389-c553-4186-8eff-465833f76e81)

**Comment by code-kay** [comment]
"auto"라는 값을 주면 에러가 뜨는 것 같습니당
"100%"라는 값을 사용하니 동일한 효과를 보면서 에러를 없앨 수 있었습니다!
참고 링크 : https://github.com/boopathi/react-svg-loader/issues/194
